services:
    sonata.admin.post:
        class: Blogger\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Blogger\BlogBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [BlogBundle]]