blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Page:index }

blog_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
      _method:  GET

blog_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
blog_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+