services:
#    blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BlogExtension
        tags:
            - { name: twig.extension }
