Blogger\BlogBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: Blogger\BlogBundle\Entity\Repository\PostRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        blog:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        image:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        tags:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        created:
            type: datetime
            nullable: false
            comment: ''
        updated:
            type: datetime
            nullable: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    oneToMany:
        comments:
            targetEntity: Blogger\BlogBundle\Entity\Comment
            mappedBy: blog
    manyToOne:
        author:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
